/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inneractive.hermes.model;
@SuppressWarnings("all")
/** connection Type used to get data */
@org.apache.avro.specific.AvroGenerated
public enum connectionType {
  UNKNOWN, WIFI, CELLULAR_UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"connectionType\",\"namespace\":\"com.inneractive.hermes.model\",\"doc\":\"connection Type used to get data\",\"symbols\":[\"UNKNOWN\",\"WIFI\",\"CELLULAR_UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
