/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inneractive.hermes.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Contains all the dimensions across all events */
@org.apache.avro.specific.AvroGenerated
public class Dimensions extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2734828643272315863L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Dimensions\",\"namespace\":\"com.inneractive.hermes.model\",\"doc\":\"Contains all the dimensions across all events\",\"fields\":[{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"EventType\",\"doc\":\"Event type is used to \",\"symbols\":[\"AD_REQUEST\",\"DEFAULT_AD\",\"IMPRESSION\",\"CLICK\",\"NO_AD\",\"AD_SERVED\",\"DEFAULT_CLICK\",\"DOWNLOAD\",\"FILTERED_AD\",\"FRAUDULENT_CLICK\",\"JOIN1\",\"JOIN2\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Dimensions> ENCODER =
      new BinaryMessageEncoder<Dimensions>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Dimensions> DECODER =
      new BinaryMessageDecoder<Dimensions>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Dimensions> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Dimensions> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Dimensions>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Dimensions to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Dimensions from a ByteBuffer. */
  public static Dimensions fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.inneractive.hermes.model.EventType eventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Dimensions() {}

  /**
   * All-args constructor.
   * @param eventType The new value for eventType
   */
  public Dimensions(com.inneractive.hermes.model.EventType eventType) {
    this.eventType = eventType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventType = (com.inneractive.hermes.model.EventType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public com.inneractive.hermes.model.EventType getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(com.inneractive.hermes.model.EventType value) {
    this.eventType = value;
  }

  /**
   * Creates a new Dimensions RecordBuilder.
   * @return A new Dimensions RecordBuilder
   */
  public static com.inneractive.hermes.model.Dimensions.Builder newBuilder() {
    return new com.inneractive.hermes.model.Dimensions.Builder();
  }

  /**
   * Creates a new Dimensions RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Dimensions RecordBuilder
   */
  public static com.inneractive.hermes.model.Dimensions.Builder newBuilder(com.inneractive.hermes.model.Dimensions.Builder other) {
    return new com.inneractive.hermes.model.Dimensions.Builder(other);
  }

  /**
   * Creates a new Dimensions RecordBuilder by copying an existing Dimensions instance.
   * @param other The existing instance to copy.
   * @return A new Dimensions RecordBuilder
   */
  public static com.inneractive.hermes.model.Dimensions.Builder newBuilder(com.inneractive.hermes.model.Dimensions other) {
    return new com.inneractive.hermes.model.Dimensions.Builder(other);
  }

  /**
   * RecordBuilder for Dimensions instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Dimensions>
    implements org.apache.avro.data.RecordBuilder<Dimensions> {

    private com.inneractive.hermes.model.EventType eventType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inneractive.hermes.model.Dimensions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Dimensions instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inneractive.hermes.model.Dimensions other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public com.inneractive.hermes.model.EventType getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.Dimensions.Builder setEventType(com.inneractive.hermes.model.EventType value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.Dimensions.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Dimensions build() {
      try {
        Dimensions record = new Dimensions();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (com.inneractive.hermes.model.EventType) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Dimensions>
    WRITER$ = (org.apache.avro.io.DatumWriter<Dimensions>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Dimensions>
    READER$ = (org.apache.avro.io.DatumReader<Dimensions>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
