/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.inneractive.hermes.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Full event contains all the data after join */
@org.apache.avro.specific.AvroGenerated
public class JoinFullEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3489360106898276679L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JoinFullEvent\",\"namespace\":\"com.inneractive.hermes.model\",\"doc\":\"Full event contains all the data after join\",\"fields\":[{\"name\":\"sessionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"generated for each request used to link with impression and clicks\"},{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"EventType\",\"doc\":\"Event type is used to \",\"symbols\":[\"AD_REQUEST\",\"DEFAULT_AD\",\"IMPRESSION\",\"CLICK\",\"NO_AD\",\"JOIN1\",\"JOIN2\"]}},{\"name\":\"publisherId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"contentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"adNetworkId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"eventTimestamp\",\"type\":\"long\"},{\"name\":\"countryCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"US\"},{\"name\":\"publisherGross\",\"type\":\"double\",\"default\":0.0},{\"name\":\"publisherNet\",\"type\":\"double\",\"default\":0.0},{\"name\":\"iaGross\",\"type\":\"double\",\"default\":0.0},{\"name\":\"iaNet\",\"type\":\"double\",\"default\":0.0},{\"name\":\"occurrences\",\"type\":\"int\",\"default\":0},{\"name\":\"iABCategories\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]},{\"name\":\"dimension1\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"value1\",\"type\":\"double\",\"default\":0.0},{\"name\":\"dimension2\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"value2\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JoinFullEvent> ENCODER =
      new BinaryMessageEncoder<JoinFullEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JoinFullEvent> DECODER =
      new BinaryMessageDecoder<JoinFullEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<JoinFullEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<JoinFullEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<JoinFullEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this JoinFullEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a JoinFullEvent from a ByteBuffer. */
  public static JoinFullEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** generated for each request used to link with impression and clicks */
  @Deprecated public java.lang.String sessionId;
  @Deprecated public com.inneractive.hermes.model.EventType eventType;
  @Deprecated public java.lang.String publisherId;
  @Deprecated public java.lang.String contentId;
  @Deprecated public java.lang.String adNetworkId;
  @Deprecated public long eventTimestamp;
  @Deprecated public java.lang.String countryCode;
  @Deprecated public double publisherGross;
  @Deprecated public double publisherNet;
  @Deprecated public double iaGross;
  @Deprecated public double iaNet;
  @Deprecated public int occurrences;
  @Deprecated public java.util.List<java.lang.String> iABCategories;
  @Deprecated public java.lang.String dimension1;
  @Deprecated public double value1;
  @Deprecated public java.lang.String dimension2;
  @Deprecated public double value2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JoinFullEvent() {}

  /**
   * All-args constructor.
   * @param sessionId generated for each request used to link with impression and clicks
   * @param eventType The new value for eventType
   * @param publisherId The new value for publisherId
   * @param contentId The new value for contentId
   * @param adNetworkId The new value for adNetworkId
   * @param eventTimestamp The new value for eventTimestamp
   * @param countryCode The new value for countryCode
   * @param publisherGross The new value for publisherGross
   * @param publisherNet The new value for publisherNet
   * @param iaGross The new value for iaGross
   * @param iaNet The new value for iaNet
   * @param occurrences The new value for occurrences
   * @param iABCategories The new value for iABCategories
   * @param dimension1 The new value for dimension1
   * @param value1 The new value for value1
   * @param dimension2 The new value for dimension2
   * @param value2 The new value for value2
   */
  public JoinFullEvent(java.lang.String sessionId, com.inneractive.hermes.model.EventType eventType, java.lang.String publisherId, java.lang.String contentId, java.lang.String adNetworkId, java.lang.Long eventTimestamp, java.lang.String countryCode, java.lang.Double publisherGross, java.lang.Double publisherNet, java.lang.Double iaGross, java.lang.Double iaNet, java.lang.Integer occurrences, java.util.List<java.lang.String> iABCategories, java.lang.String dimension1, java.lang.Double value1, java.lang.String dimension2, java.lang.Double value2) {
    this.sessionId = sessionId;
    this.eventType = eventType;
    this.publisherId = publisherId;
    this.contentId = contentId;
    this.adNetworkId = adNetworkId;
    this.eventTimestamp = eventTimestamp;
    this.countryCode = countryCode;
    this.publisherGross = publisherGross;
    this.publisherNet = publisherNet;
    this.iaGross = iaGross;
    this.iaNet = iaNet;
    this.occurrences = occurrences;
    this.iABCategories = iABCategories;
    this.dimension1 = dimension1;
    this.value1 = value1;
    this.dimension2 = dimension2;
    this.value2 = value2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionId;
    case 1: return eventType;
    case 2: return publisherId;
    case 3: return contentId;
    case 4: return adNetworkId;
    case 5: return eventTimestamp;
    case 6: return countryCode;
    case 7: return publisherGross;
    case 8: return publisherNet;
    case 9: return iaGross;
    case 10: return iaNet;
    case 11: return occurrences;
    case 12: return iABCategories;
    case 13: return dimension1;
    case 14: return value1;
    case 15: return dimension2;
    case 16: return value2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionId = (java.lang.String)value$; break;
    case 1: eventType = (com.inneractive.hermes.model.EventType)value$; break;
    case 2: publisherId = (java.lang.String)value$; break;
    case 3: contentId = (java.lang.String)value$; break;
    case 4: adNetworkId = (java.lang.String)value$; break;
    case 5: eventTimestamp = (java.lang.Long)value$; break;
    case 6: countryCode = (java.lang.String)value$; break;
    case 7: publisherGross = (java.lang.Double)value$; break;
    case 8: publisherNet = (java.lang.Double)value$; break;
    case 9: iaGross = (java.lang.Double)value$; break;
    case 10: iaNet = (java.lang.Double)value$; break;
    case 11: occurrences = (java.lang.Integer)value$; break;
    case 12: iABCategories = (java.util.List<java.lang.String>)value$; break;
    case 13: dimension1 = (java.lang.String)value$; break;
    case 14: value1 = (java.lang.Double)value$; break;
    case 15: dimension2 = (java.lang.String)value$; break;
    case 16: value2 = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessionId' field.
   * @return generated for each request used to link with impression and clicks
   */
  public java.lang.String getSessionId() {
    return sessionId;
  }

  /**
   * Sets the value of the 'sessionId' field.
   * generated for each request used to link with impression and clicks
   * @param value the value to set.
   */
  public void setSessionId(java.lang.String value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public com.inneractive.hermes.model.EventType getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(com.inneractive.hermes.model.EventType value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'publisherId' field.
   * @return The value of the 'publisherId' field.
   */
  public java.lang.String getPublisherId() {
    return publisherId;
  }

  /**
   * Sets the value of the 'publisherId' field.
   * @param value the value to set.
   */
  public void setPublisherId(java.lang.String value) {
    this.publisherId = value;
  }

  /**
   * Gets the value of the 'contentId' field.
   * @return The value of the 'contentId' field.
   */
  public java.lang.String getContentId() {
    return contentId;
  }

  /**
   * Sets the value of the 'contentId' field.
   * @param value the value to set.
   */
  public void setContentId(java.lang.String value) {
    this.contentId = value;
  }

  /**
   * Gets the value of the 'adNetworkId' field.
   * @return The value of the 'adNetworkId' field.
   */
  public java.lang.String getAdNetworkId() {
    return adNetworkId;
  }

  /**
   * Sets the value of the 'adNetworkId' field.
   * @param value the value to set.
   */
  public void setAdNetworkId(java.lang.String value) {
    this.adNetworkId = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return The value of the 'eventTimestamp' field.
   */
  public java.lang.Long getEventTimestamp() {
    return eventTimestamp;
  }

  /**
   * Sets the value of the 'eventTimestamp' field.
   * @param value the value to set.
   */
  public void setEventTimestamp(java.lang.Long value) {
    this.eventTimestamp = value;
  }

  /**
   * Gets the value of the 'countryCode' field.
   * @return The value of the 'countryCode' field.
   */
  public java.lang.String getCountryCode() {
    return countryCode;
  }

  /**
   * Sets the value of the 'countryCode' field.
   * @param value the value to set.
   */
  public void setCountryCode(java.lang.String value) {
    this.countryCode = value;
  }

  /**
   * Gets the value of the 'publisherGross' field.
   * @return The value of the 'publisherGross' field.
   */
  public java.lang.Double getPublisherGross() {
    return publisherGross;
  }

  /**
   * Sets the value of the 'publisherGross' field.
   * @param value the value to set.
   */
  public void setPublisherGross(java.lang.Double value) {
    this.publisherGross = value;
  }

  /**
   * Gets the value of the 'publisherNet' field.
   * @return The value of the 'publisherNet' field.
   */
  public java.lang.Double getPublisherNet() {
    return publisherNet;
  }

  /**
   * Sets the value of the 'publisherNet' field.
   * @param value the value to set.
   */
  public void setPublisherNet(java.lang.Double value) {
    this.publisherNet = value;
  }

  /**
   * Gets the value of the 'iaGross' field.
   * @return The value of the 'iaGross' field.
   */
  public java.lang.Double getIaGross() {
    return iaGross;
  }

  /**
   * Sets the value of the 'iaGross' field.
   * @param value the value to set.
   */
  public void setIaGross(java.lang.Double value) {
    this.iaGross = value;
  }

  /**
   * Gets the value of the 'iaNet' field.
   * @return The value of the 'iaNet' field.
   */
  public java.lang.Double getIaNet() {
    return iaNet;
  }

  /**
   * Sets the value of the 'iaNet' field.
   * @param value the value to set.
   */
  public void setIaNet(java.lang.Double value) {
    this.iaNet = value;
  }

  /**
   * Gets the value of the 'occurrences' field.
   * @return The value of the 'occurrences' field.
   */
  public java.lang.Integer getOccurrences() {
    return occurrences;
  }

  /**
   * Sets the value of the 'occurrences' field.
   * @param value the value to set.
   */
  public void setOccurrences(java.lang.Integer value) {
    this.occurrences = value;
  }

  /**
   * Gets the value of the 'iABCategories' field.
   * @return The value of the 'iABCategories' field.
   */
  public java.util.List<java.lang.String> getIABCategories() {
    return iABCategories;
  }

  /**
   * Sets the value of the 'iABCategories' field.
   * @param value the value to set.
   */
  public void setIABCategories(java.util.List<java.lang.String> value) {
    this.iABCategories = value;
  }

  /**
   * Gets the value of the 'dimension1' field.
   * @return The value of the 'dimension1' field.
   */
  public java.lang.String getDimension1() {
    return dimension1;
  }

  /**
   * Sets the value of the 'dimension1' field.
   * @param value the value to set.
   */
  public void setDimension1(java.lang.String value) {
    this.dimension1 = value;
  }

  /**
   * Gets the value of the 'value1' field.
   * @return The value of the 'value1' field.
   */
  public java.lang.Double getValue1() {
    return value1;
  }

  /**
   * Sets the value of the 'value1' field.
   * @param value the value to set.
   */
  public void setValue1(java.lang.Double value) {
    this.value1 = value;
  }

  /**
   * Gets the value of the 'dimension2' field.
   * @return The value of the 'dimension2' field.
   */
  public java.lang.String getDimension2() {
    return dimension2;
  }

  /**
   * Sets the value of the 'dimension2' field.
   * @param value the value to set.
   */
  public void setDimension2(java.lang.String value) {
    this.dimension2 = value;
  }

  /**
   * Gets the value of the 'value2' field.
   * @return The value of the 'value2' field.
   */
  public java.lang.Double getValue2() {
    return value2;
  }

  /**
   * Sets the value of the 'value2' field.
   * @param value the value to set.
   */
  public void setValue2(java.lang.Double value) {
    this.value2 = value;
  }

  /**
   * Creates a new JoinFullEvent RecordBuilder.
   * @return A new JoinFullEvent RecordBuilder
   */
  public static com.inneractive.hermes.model.JoinFullEvent.Builder newBuilder() {
    return new com.inneractive.hermes.model.JoinFullEvent.Builder();
  }

  /**
   * Creates a new JoinFullEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JoinFullEvent RecordBuilder
   */
  public static com.inneractive.hermes.model.JoinFullEvent.Builder newBuilder(com.inneractive.hermes.model.JoinFullEvent.Builder other) {
    return new com.inneractive.hermes.model.JoinFullEvent.Builder(other);
  }

  /**
   * Creates a new JoinFullEvent RecordBuilder by copying an existing JoinFullEvent instance.
   * @param other The existing instance to copy.
   * @return A new JoinFullEvent RecordBuilder
   */
  public static com.inneractive.hermes.model.JoinFullEvent.Builder newBuilder(com.inneractive.hermes.model.JoinFullEvent other) {
    return new com.inneractive.hermes.model.JoinFullEvent.Builder(other);
  }

  /**
   * RecordBuilder for JoinFullEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JoinFullEvent>
    implements org.apache.avro.data.RecordBuilder<JoinFullEvent> {

    /** generated for each request used to link with impression and clicks */
    private java.lang.String sessionId;
    private com.inneractive.hermes.model.EventType eventType;
    private java.lang.String publisherId;
    private java.lang.String contentId;
    private java.lang.String adNetworkId;
    private long eventTimestamp;
    private java.lang.String countryCode;
    private double publisherGross;
    private double publisherNet;
    private double iaGross;
    private double iaNet;
    private int occurrences;
    private java.util.List<java.lang.String> iABCategories;
    private java.lang.String dimension1;
    private double value1;
    private java.lang.String dimension2;
    private double value2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.inneractive.hermes.model.JoinFullEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[2].schema(), other.publisherId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.contentId)) {
        this.contentId = data().deepCopy(fields()[3].schema(), other.contentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.adNetworkId)) {
        this.adNetworkId = data().deepCopy(fields()[4].schema(), other.adNetworkId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[5].schema(), other.eventTimestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.countryCode)) {
        this.countryCode = data().deepCopy(fields()[6].schema(), other.countryCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.publisherGross)) {
        this.publisherGross = data().deepCopy(fields()[7].schema(), other.publisherGross);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.publisherNet)) {
        this.publisherNet = data().deepCopy(fields()[8].schema(), other.publisherNet);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.iaGross)) {
        this.iaGross = data().deepCopy(fields()[9].schema(), other.iaGross);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.iaNet)) {
        this.iaNet = data().deepCopy(fields()[10].schema(), other.iaNet);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.occurrences)) {
        this.occurrences = data().deepCopy(fields()[11].schema(), other.occurrences);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.iABCategories)) {
        this.iABCategories = data().deepCopy(fields()[12].schema(), other.iABCategories);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.dimension1)) {
        this.dimension1 = data().deepCopy(fields()[13].schema(), other.dimension1);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.value1)) {
        this.value1 = data().deepCopy(fields()[14].schema(), other.value1);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.dimension2)) {
        this.dimension2 = data().deepCopy(fields()[15].schema(), other.dimension2);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.value2)) {
        this.value2 = data().deepCopy(fields()[16].schema(), other.value2);
        fieldSetFlags()[16] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JoinFullEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.inneractive.hermes.model.JoinFullEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publisherId)) {
        this.publisherId = data().deepCopy(fields()[2].schema(), other.publisherId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.contentId)) {
        this.contentId = data().deepCopy(fields()[3].schema(), other.contentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.adNetworkId)) {
        this.adNetworkId = data().deepCopy(fields()[4].schema(), other.adNetworkId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[5].schema(), other.eventTimestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.countryCode)) {
        this.countryCode = data().deepCopy(fields()[6].schema(), other.countryCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.publisherGross)) {
        this.publisherGross = data().deepCopy(fields()[7].schema(), other.publisherGross);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.publisherNet)) {
        this.publisherNet = data().deepCopy(fields()[8].schema(), other.publisherNet);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.iaGross)) {
        this.iaGross = data().deepCopy(fields()[9].schema(), other.iaGross);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.iaNet)) {
        this.iaNet = data().deepCopy(fields()[10].schema(), other.iaNet);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.occurrences)) {
        this.occurrences = data().deepCopy(fields()[11].schema(), other.occurrences);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.iABCategories)) {
        this.iABCategories = data().deepCopy(fields()[12].schema(), other.iABCategories);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.dimension1)) {
        this.dimension1 = data().deepCopy(fields()[13].schema(), other.dimension1);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.value1)) {
        this.value1 = data().deepCopy(fields()[14].schema(), other.value1);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.dimension2)) {
        this.dimension2 = data().deepCopy(fields()[15].schema(), other.dimension2);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.value2)) {
        this.value2 = data().deepCopy(fields()[16].schema(), other.value2);
        fieldSetFlags()[16] = true;
      }
    }

    /**
      * Gets the value of the 'sessionId' field.
      * generated for each request used to link with impression and clicks
      * @return The value.
      */
    public java.lang.String getSessionId() {
      return sessionId;
    }

    /**
      * Sets the value of the 'sessionId' field.
      * generated for each request used to link with impression and clicks
      * @param value The value of 'sessionId'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setSessionId(java.lang.String value) {
      validate(fields()[0], value);
      this.sessionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionId' field has been set.
      * generated for each request used to link with impression and clicks
      * @return True if the 'sessionId' field has been set, false otherwise.
      */
    public boolean hasSessionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sessionId' field.
      * generated for each request used to link with impression and clicks
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public com.inneractive.hermes.model.EventType getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setEventType(com.inneractive.hermes.model.EventType value) {
      validate(fields()[1], value);
      this.eventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisherId' field.
      * @return The value.
      */
    public java.lang.String getPublisherId() {
      return publisherId;
    }

    /**
      * Sets the value of the 'publisherId' field.
      * @param value The value of 'publisherId'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setPublisherId(java.lang.String value) {
      validate(fields()[2], value);
      this.publisherId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publisherId' field has been set.
      * @return True if the 'publisherId' field has been set, false otherwise.
      */
    public boolean hasPublisherId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'publisherId' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearPublisherId() {
      publisherId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'contentId' field.
      * @return The value.
      */
    public java.lang.String getContentId() {
      return contentId;
    }

    /**
      * Sets the value of the 'contentId' field.
      * @param value The value of 'contentId'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setContentId(java.lang.String value) {
      validate(fields()[3], value);
      this.contentId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'contentId' field has been set.
      * @return True if the 'contentId' field has been set, false otherwise.
      */
    public boolean hasContentId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'contentId' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearContentId() {
      contentId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'adNetworkId' field.
      * @return The value.
      */
    public java.lang.String getAdNetworkId() {
      return adNetworkId;
    }

    /**
      * Sets the value of the 'adNetworkId' field.
      * @param value The value of 'adNetworkId'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setAdNetworkId(java.lang.String value) {
      validate(fields()[4], value);
      this.adNetworkId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'adNetworkId' field has been set.
      * @return True if the 'adNetworkId' field has been set, false otherwise.
      */
    public boolean hasAdNetworkId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'adNetworkId' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearAdNetworkId() {
      adNetworkId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * @return The value.
      */
    public java.lang.Long getEventTimestamp() {
      return eventTimestamp;
    }

    /**
      * Sets the value of the 'eventTimestamp' field.
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setEventTimestamp(long value) {
      validate(fields()[5], value);
      this.eventTimestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearEventTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'countryCode' field.
      * @return The value.
      */
    public java.lang.String getCountryCode() {
      return countryCode;
    }

    /**
      * Sets the value of the 'countryCode' field.
      * @param value The value of 'countryCode'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setCountryCode(java.lang.String value) {
      validate(fields()[6], value);
      this.countryCode = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'countryCode' field has been set.
      * @return True if the 'countryCode' field has been set, false otherwise.
      */
    public boolean hasCountryCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'countryCode' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearCountryCode() {
      countryCode = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisherGross' field.
      * @return The value.
      */
    public java.lang.Double getPublisherGross() {
      return publisherGross;
    }

    /**
      * Sets the value of the 'publisherGross' field.
      * @param value The value of 'publisherGross'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setPublisherGross(double value) {
      validate(fields()[7], value);
      this.publisherGross = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'publisherGross' field has been set.
      * @return True if the 'publisherGross' field has been set, false otherwise.
      */
    public boolean hasPublisherGross() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'publisherGross' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearPublisherGross() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisherNet' field.
      * @return The value.
      */
    public java.lang.Double getPublisherNet() {
      return publisherNet;
    }

    /**
      * Sets the value of the 'publisherNet' field.
      * @param value The value of 'publisherNet'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setPublisherNet(double value) {
      validate(fields()[8], value);
      this.publisherNet = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'publisherNet' field has been set.
      * @return True if the 'publisherNet' field has been set, false otherwise.
      */
    public boolean hasPublisherNet() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'publisherNet' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearPublisherNet() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'iaGross' field.
      * @return The value.
      */
    public java.lang.Double getIaGross() {
      return iaGross;
    }

    /**
      * Sets the value of the 'iaGross' field.
      * @param value The value of 'iaGross'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setIaGross(double value) {
      validate(fields()[9], value);
      this.iaGross = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'iaGross' field has been set.
      * @return True if the 'iaGross' field has been set, false otherwise.
      */
    public boolean hasIaGross() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'iaGross' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearIaGross() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'iaNet' field.
      * @return The value.
      */
    public java.lang.Double getIaNet() {
      return iaNet;
    }

    /**
      * Sets the value of the 'iaNet' field.
      * @param value The value of 'iaNet'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setIaNet(double value) {
      validate(fields()[10], value);
      this.iaNet = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'iaNet' field has been set.
      * @return True if the 'iaNet' field has been set, false otherwise.
      */
    public boolean hasIaNet() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'iaNet' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearIaNet() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurrences' field.
      * @return The value.
      */
    public java.lang.Integer getOccurrences() {
      return occurrences;
    }

    /**
      * Sets the value of the 'occurrences' field.
      * @param value The value of 'occurrences'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setOccurrences(int value) {
      validate(fields()[11], value);
      this.occurrences = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'occurrences' field has been set.
      * @return True if the 'occurrences' field has been set, false otherwise.
      */
    public boolean hasOccurrences() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'occurrences' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearOccurrences() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'iABCategories' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getIABCategories() {
      return iABCategories;
    }

    /**
      * Sets the value of the 'iABCategories' field.
      * @param value The value of 'iABCategories'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setIABCategories(java.util.List<java.lang.String> value) {
      validate(fields()[12], value);
      this.iABCategories = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'iABCategories' field has been set.
      * @return True if the 'iABCategories' field has been set, false otherwise.
      */
    public boolean hasIABCategories() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'iABCategories' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearIABCategories() {
      iABCategories = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'dimension1' field.
      * @return The value.
      */
    public java.lang.String getDimension1() {
      return dimension1;
    }

    /**
      * Sets the value of the 'dimension1' field.
      * @param value The value of 'dimension1'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setDimension1(java.lang.String value) {
      validate(fields()[13], value);
      this.dimension1 = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'dimension1' field has been set.
      * @return True if the 'dimension1' field has been set, false otherwise.
      */
    public boolean hasDimension1() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'dimension1' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearDimension1() {
      dimension1 = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'value1' field.
      * @return The value.
      */
    public java.lang.Double getValue1() {
      return value1;
    }

    /**
      * Sets the value of the 'value1' field.
      * @param value The value of 'value1'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setValue1(double value) {
      validate(fields()[14], value);
      this.value1 = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'value1' field has been set.
      * @return True if the 'value1' field has been set, false otherwise.
      */
    public boolean hasValue1() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'value1' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearValue1() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'dimension2' field.
      * @return The value.
      */
    public java.lang.String getDimension2() {
      return dimension2;
    }

    /**
      * Sets the value of the 'dimension2' field.
      * @param value The value of 'dimension2'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setDimension2(java.lang.String value) {
      validate(fields()[15], value);
      this.dimension2 = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'dimension2' field has been set.
      * @return True if the 'dimension2' field has been set, false otherwise.
      */
    public boolean hasDimension2() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'dimension2' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearDimension2() {
      dimension2 = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'value2' field.
      * @return The value.
      */
    public java.lang.Double getValue2() {
      return value2;
    }

    /**
      * Sets the value of the 'value2' field.
      * @param value The value of 'value2'.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder setValue2(double value) {
      validate(fields()[16], value);
      this.value2 = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'value2' field has been set.
      * @return True if the 'value2' field has been set, false otherwise.
      */
    public boolean hasValue2() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'value2' field.
      * @return This builder.
      */
    public com.inneractive.hermes.model.JoinFullEvent.Builder clearValue2() {
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JoinFullEvent build() {
      try {
        JoinFullEvent record = new JoinFullEvent();
        record.sessionId = fieldSetFlags()[0] ? this.sessionId : (java.lang.String) defaultValue(fields()[0]);
        record.eventType = fieldSetFlags()[1] ? this.eventType : (com.inneractive.hermes.model.EventType) defaultValue(fields()[1]);
        record.publisherId = fieldSetFlags()[2] ? this.publisherId : (java.lang.String) defaultValue(fields()[2]);
        record.contentId = fieldSetFlags()[3] ? this.contentId : (java.lang.String) defaultValue(fields()[3]);
        record.adNetworkId = fieldSetFlags()[4] ? this.adNetworkId : (java.lang.String) defaultValue(fields()[4]);
        record.eventTimestamp = fieldSetFlags()[5] ? this.eventTimestamp : (java.lang.Long) defaultValue(fields()[5]);
        record.countryCode = fieldSetFlags()[6] ? this.countryCode : (java.lang.String) defaultValue(fields()[6]);
        record.publisherGross = fieldSetFlags()[7] ? this.publisherGross : (java.lang.Double) defaultValue(fields()[7]);
        record.publisherNet = fieldSetFlags()[8] ? this.publisherNet : (java.lang.Double) defaultValue(fields()[8]);
        record.iaGross = fieldSetFlags()[9] ? this.iaGross : (java.lang.Double) defaultValue(fields()[9]);
        record.iaNet = fieldSetFlags()[10] ? this.iaNet : (java.lang.Double) defaultValue(fields()[10]);
        record.occurrences = fieldSetFlags()[11] ? this.occurrences : (java.lang.Integer) defaultValue(fields()[11]);
        record.iABCategories = fieldSetFlags()[12] ? this.iABCategories : (java.util.List<java.lang.String>) defaultValue(fields()[12]);
        record.dimension1 = fieldSetFlags()[13] ? this.dimension1 : (java.lang.String) defaultValue(fields()[13]);
        record.value1 = fieldSetFlags()[14] ? this.value1 : (java.lang.Double) defaultValue(fields()[14]);
        record.dimension2 = fieldSetFlags()[15] ? this.dimension2 : (java.lang.String) defaultValue(fields()[15]);
        record.value2 = fieldSetFlags()[16] ? this.value2 : (java.lang.Double) defaultValue(fields()[16]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JoinFullEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<JoinFullEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JoinFullEvent>
    READER$ = (org.apache.avro.io.DatumReader<JoinFullEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
